spring:
  profiles:
    active: dev
    
spring:
  profiles: dev
  server:
    port: 9999
    
spring:
  profiles: test
  server:
    port: 8888
    
spring:
  profiles: produce
  server:
    port: 7777