spring:
  profiles:
    active: dev
    
spring:
  profiles: dev
  server:
    port: 8001
    
spring:
  profiles: test
  server:
    port: 8011
    
spring:
  profiles: produce
  server:
    port: 8111